export type Product = {
    additionalProductInformation: string[],
    additionalProductVariants: string[],
    brandId: string,
    categoryId: string,
    colours: string,
    condition: string,
    insertTime: string,
    isDeleted: boolean,
    isLocked: boolean,
    isVisible: boolean,
    marketStatus: string,
    originOrganisationOrderId: string,
    organisationDescription: string,
    organisationDescriptionHtml: string,
    organizationId: string,
    organisationImageNames: string[],
    organisationProductType: string,
    originLineItemId: string,
    originProductId: string,
    ownerid: string,
    purchaseTime: string,
    rrp: number,
    size: string,
    title: string,
    value: number,
    engagementChecks: string[],
    marketplaceOffers: string[],
    payoutOption: string,
    parcelSize: string,
    shippingLabelCost: number,
    id:string,
}